name: Build Windows EXE
on: push  # Runs on every git push

jobs:
  build:
    runs-on: windows-latest  # Uses a Windows VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Copies your repo files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Change to your Python version

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile videopoker.py  # Change flags as needed

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: YourApp-EXE
          path: dist/your_script.exe  # Path to the generated EXE
