name: Build Windows EXE
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Debug - List files
        run: dir

      - name: Build EXE
        run: |
          pyinstaller --onefile videopoker.py
          dir dist\  # Verify the EXE exists

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: YourApp-EXE
          path: dist/videopoker.exe  # Double-check this path!
